feat: возможность создания p2p request-а
LaGGgggg/yp_p2p_api pull request #11
Opened 2024-02-24 17:32 UTC by Roman821

**core\config.py**: добавил scope "p2p_request"
**core\main.py**: добавил новый модуль p2p_request в импорт маршрутов. Теперь маршруты из p2p_request также включены в основное приложение с помощи p2p_request.router. 
**core\chemas.py**:  Внесены изменения и добавлен новый функционал, связанный с моделью P2PRequest. 
**migrations\env.py**: fix конфигурации alimbic-a который позволяет работать с полями sqlalchemy utils 
**routers\p2p_request.py**: добавлен новый файл p2p_request.py с реализацией функционала, связанного с созданием запросов типа p2p. 
**sql\crud.py**: добавлен новый класс P2PRequestCrud, который расширяет функциональность базового класса BaseCrud для работы P2PRequest. 
**sql\models.py**:  добавлен новый класс P2PRequest для представления данных о запросах p2p. В этот класс были добавлены новые столбцы, такие как repository_link, comment, review_state, и publication_date, чтобы отражать свойства p2p-запросов. Использован ChoiceType для review_state для ограничения возможных значений. 
**requirements.txt**: используем SQLAlchemy-Utils

2024-02-25 05:25 UTC, LaGGgggg requested changes
Нужны некоторые доработки (не функциональные), а так всё хорошо

2024-02-25 05:25 UTC, LaGGgggg commented on API/routers/p2p_request.py
> +SETTINGS = get_settings()
`SETTINGS` не используется в дальнейшем, лишний код

2024-02-25 05:25 UTC, LaGGgggg commented on API/routers/p2p_request.py
> +from sql.database import get_db, get_db_not_dependency
`get_db_not_dependency` не используется в дальнейшем, лишний импорт

2024-02-25 05:25 UTC, LaGGgggg commented on API/core/schemas.py
> +
Это что за непонятные пустые строки? Просто откуда это и какую цель преследует?

2024-02-25 05:28 UTC, LaGGgggg commented
И опечатки в [commit-е](https://github.com/LaGGgggg/yp_p2p_api/pull/11/commits/44944facdfab26fb1f0b8c56232985a756c61f45), ну как так-то? ("alimbic-a", "core\chemas.py:", ...)

2024-02-25 13:42 UTC, LaGGgggg submitted a review, later dismissed
Всё сделано, можно вносить в `dev`

2024-02-26 14:26 UTC, alinkalina approved these changes, later dismissed
Что ж, хорошая работа, **Рома молодец**)

2024-02-26 16:15 UTC, alinkalina commented
Хотя я тут вчиталась, может добавить `nullable=False` в модель? Кажется это не помешает...

2024-02-26 16:20 UTC, LaGGgggg commented
> Хотя я тут вчиталась, может добавить `nullable=False` в модель? Кажется это не помешает...

Однозначно нужно, закинешь commit?

2024-02-26 17:35 UTC, alinkalina commented
Сделала, по-моему колонка с комментарием может быть пустой

2024-02-26 18:00 UTC, LaGGgggg commented
Хм, а я вот думаю, что лучше поставить `nullable=False`, но при этом добавить `default=''`. Таким образом мы исключим возможность ошибки с null значением (недоглядит кто-нибудь, напишет косячный код, через пару месяцев вылезет внезапная ошибка), но при этом, по сути, оставим поле необязательным

2024-02-26 19:01 UTC, LaGGgggg submitted a review, later dismissed
Всё хорошо, закидываем в `dev`

2024-02-26 19:03 UTC, alinkalina approved these changes, later dismissed
Да, можно закрывать)

2024-02-26 19:40 UTC, alinkalina approved these changes
Всё ок

2024-02-26 19:44 UTC, LaGGgggg approved these changes

2024-02-26 19:45 UTC, merged