Feat: система регистрации
LaGGgggg/yp_p2p_api pull request #6
Opened 2024-02-18 11:31 UTC by Roman821

Тык-тык, клац-клац ⌨️
Пара бессонных ночей ✨
Дядя Никита проверит и закинет в ветку this изменения 💅

2024-02-18 11:44 UTC, LaGGgggg requested changes
В целом всё ок, пункты из ТЗ задачи выполнены, всё работает, молодец!
***(но всё равно по вопросикам из review пройдись)***
Ах да, коммиты, мне не очень понравилось как они написаны. Во-первых, они оставляют вопросы относительно того, что именно поменялось. Во-вторых, там есть фактическая ошибка. Но, так как это первый опыт, я особо не докапываюсь.
Всё остальное мне понравилось

2024-02-18 11:44 UTC, LaGGgggg commented on API/routers/users.py
> +    # return new_user
Это что такое? Мёртвый код? Серьёзно?

2024-02-18 11:44 UTC, LaGGgggg commented on API/routers/users.py
> +        ), pwd_context))
А если написать так:
```python
return schemas.User.from_orm(crud.create_user(
    db, schemas.UserCreate(username=username, password=password, discord_id=discord_id), pwd_context
))
```
Не будет ли лучше выглядеть? Звучит как вкусовщина, поэтому это не претензия, а предложение. Однако, мне кажется что в моём варианте чуть понятнее выглядит за счёт `pwd_context`, который не висит непонятно где

2024-02-18 11:44 UTC, LaGGgggg commented on API/routers/users.py
> +        current_user: models.User = Security(login_manager, scopes=['register']),
Думаю, что `current_user` лучше заменить на `_`, так как мы этот аргумент в функции не используем (но удалять мы его не будем, так как он нужен для валидации scopes пользователя силами FastAPI)
P.S. Это где-то в PEP-8, мне кажется, прописано, для неиспользуемых аргументов/переменных используется `_` в качестве названия

2024-02-18 15:57 UTC, Roman821 commented on API/routers/users.py
> +    # return new_user
Фикс-фикс *magic*
Всё исправили 👌

2024-02-18 15:58 UTC, Roman821 commented on API/routers/users.py
> +        ), pwd_context))
Теперь выглядит лучше)) 😸

2024-02-18 15:59 UTC, Roman821 commented on API/routers/users.py
> +        current_user: models.User = Security(login_manager, scopes=['register']),
Замениль 🌵

2024-02-18 16:03 UTC, LaGGgggg approved these changes

2024-02-19 09:31 UTC, alinkalina approved these changes
Откровенно говоря, не стала сильно вдаваться в подробности, что конкретно тут происходит, но судя по тому, что это **Система регистрации** видимо что-то важное)) Ну а вообще по-моему **всё круто**!

2024-02-19 13:10 UTC, merged