feat: ненулевые значения
LaGGgggg/yp_p2p_api pull request #8
Opened 2024-02-20 20:28 UTC by alinkalina

Наверняка тут всё не так просто) но я пока больше не знаю, что можно сделать.
По крайней мере, **вроде бы** всё работает как надо 🙄

2024-02-21 11:20 UTC, LaGGgggg commented
Да, всё действительно работает, всё действительно так просто.
Но, работает оно только у тех, кто создаст **миграции**, а в ветке их нет, нужно создать.
И почему-то проигнорирована модель `UserToScope`, нужно это дело исправить.

Оценил, что в `id` `nullable=False` добавлено не было, там это действительно **не** нужно, так как при `primary_key=True` `nullable=False` автоматически.
А вот по поводу [`is_active`](https://github.com/LaGGgggg/yp_p2p_api/blob/212144b46579089b6249f6bf9551e3ae1017678e/API/sql/models.py#L24) у меня с собой возник спор. Технически, да, это поле будет установлено автоматически, пустым оно не будет из-за того, что его забыли указать, задача выполнена. Но, технически, установить туда null возможно. Я не смог прийти к однозначному выводу по этому поводу, думаю, что оставим как есть.

At all, хорошо, лайк))

2024-02-21 11:30 UTC, LaGGgggg requested changes
Нужно доделать:
- [ ] Обновить аналогичным образом UserToScope.
- [x] Добавить новые миграции.

2024-02-23 09:38 UTC, LaGGgggg approved these changes
Всё работает, всё хорошо, можно вносить в `dev`.
Единственное, название [коммита](https://github.com/LaGGgggg/yp_p2p_api/pull/8/commits/78e4d93509460f5c4b8121538e0bd95c6702532e) не в полной мере отражает изменения (хотя в теле коммита всё расписано))

2024-02-24 16:45 UTC, Roman821 approved these changes
Just одобряю!
Как вроде все задачи по ТЗ выполнены ';)

2024-02-25 05:12 UTC, merged